### ISSUE TITLE
Invalid call to git-mkver

### ISSUE THREAD

**Issue by thclark** [octue/check-semantic-version#18]
### What is the current behavior?

I've updated the release, because I needed to use a version of poetry compatible with the latest pyproject.toml standard.

I made the release (1.0.1) and am now getting the following error when running:
```
/usr/bin/docker run --name octuechecksemanticversion101_077300 --label 1af1a0 --workdir /github/workspace --rm -e "INPUT_PATH" -e "INPUT_BREAKING_CHANGE_INDICATED_BY" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e
[2024-07-25 11:23:5[6](https://github.com/octue/amy/actions/runs/10092701070/job/27908459394#step:4:7),040 | INFO | check_semantic_version.check_semantic_version] Getting current version from '/github/workspace/pyproject.toml'.
[2024-07-25 11:23:56,[7](https://github.com/octue/amy/actions/runs/10092701070/job/27908459394#step:4:8)32 | WARNING | check_semantic_version.check_semantic_version] No `mkver.conf` file found. Generating one instead.
Traceback (most recent call last):
  File "/usr/local/bin/check-semantic-version", line [8](https://github.com/octue/amy/actions/runs/10092701070/job/27908459394#step:4:9), in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/check_semantic_version/cli.py", line 30, in main
    match = check_versions_match(args.path, args.breaking_change_indicated_by)
  File "/usr/local/lib/python3.[10](https://github.com/octue/amy/actions/runs/10092701070/job/27908459394#step:4:11)/site-packages/check_semantic_version/check_semantic_version.py", line 57, in check_versions_match
    expected_semantic_version = _get_expected_semantic_version(
  File "/usr/local/lib/python3.10/site-packages/check_semantic_version/check_semantic_version.py", line 141, in _get_expected_semantic_version
    raise CalledProcessError(returncode=e.returncode, cmd=e.cmd, output=e.output, stderr=e.stderr) from None
check_semantic_version.check_semantic_version.CalledProcessError: Command '['git-mkver', '-c', '/tmp/tmpkh_32qvh', 'next']' returned non-zero exit status 1. Stderr: b''
```

### What is the expected behavior?

Should work as normal

### Other information

https://github.com/octue/amy/actions/runs/10092701070

**Comment by cortadocodes** [comment]
I can reproduce this error by running this in a repository on my local:
```
docker run -v $(pwd):/code -it octue/check-semantic-version:1.0.3 /code/pyproject.toml

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[2024-10-08 16:37:58,448 | INFO | check_semantic_version.check_semantic_version] Getting current version from '/code/pyproject.toml'.
[2024-10-08 16:37:59,039 | WARNING | check_semantic_version.check_semantic_version] No `mkver.conf` file found. Generating one instead.
[2024-10-08 16:37:59,040 | INFO | check_semantic_version.check_semantic_version] `mkver.conf` file created at '/tmp/tmpsy3s4zw5'.
Traceback (most recent call last):
  File "/usr/local/bin/check-semantic-version", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/check_semantic_version/cli.py", line 30, in main
    match = check_versions_match(args.path, args.breaking_change_indicated_by)
  File "/usr/local/lib/python3.10/site-packages/check_semantic_version/check_semantic_version.py", line 57, in check_versions_match
    expected_semantic_version = _get_expected_semantic_version(
  File "/usr/local/lib/python3.10/site-packages/check_semantic_version/check_semantic_version.py", line 143, in _get_expected_semantic_version
    raise CalledProcessError(returncode=e.returncode, cmd=e.cmd, output=e.output, stderr=e.stderr) from None
check_semantic_version.check_semantic_version.CalledProcessError: Command '['git-mkver', '-c', '/tmp/tmpsy3s4zw5', 'next']' returned non-zero exit status 1. Stderr: b''

```

**Comment by cortadocodes** [comment]
However, if I shell into the container and call the CLI in there, it works:

```
docker run -v $(pwd):/code -it --entrypoint=/bin/bash octue/check-semantic-version:1.0.3

check-semantic-version pyproject.toml 
[2024-10-08 16:41:37,622 | INFO | check_semantic_version.check_semantic_version] Getting current version from '/code/pyproject.toml'.
[2024-10-08 16:41:38,203 | WARNING | check_semantic_version.check_semantic_version] No `mkver.conf` file found. Generating one instead.
[2024-10-08 16:41:38,204 | INFO | check_semantic_version.check_semantic_version] `mkver.conf` file created at '/tmp/tmpashc30yv'.
VERSION PASSED CHECKS: The current version is the same as the expected semantic version: 0.4.1.

```

**Comment by cortadocodes** [comment]
Curiously, I can run `git-mkver next` from my local:
```
docker run -v $(pwd):/code --workdir=/code \
  --entrypoint=git-mkver \
  octue/check-semantic-version:1.0.3 next

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
0.1.0+improve-shell-workflow.967ee40
```

**Comment by cortadocodes** [comment]
The newly-released version `1.0.4` seems to fix the issue.

```
docker run -v $(pwd):/code octue/check-semantic-version:1.0.4 /code/pyproject.toml

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[2024-10-09 15:39:53,537 | INFO | check_semantic_version.check_semantic_version] Getting current version from '/code/pyproject.toml'.
[2024-10-09 15:39:54,126 | INFO | check_semantic_version.check_semantic_version] Current version: 0.4.1
[2024-10-09 15:39:54,127 | WARNING | check_semantic_version.check_semantic_version] No `mkver.conf` file found. Generating one instead.
[2024-10-09 15:39:54,128 | INFO | check_semantic_version.check_semantic_version] `mkver.conf` file created at '/tmp/tmplcqjcadd'.
VERSION FAILED CHECKS: The current version (0.4.1) is different from the expected semantic version (0.1.0).
```

**Comment by cortadocodes** [comment]
The above runs locally but the action still fails with the same error:
```
[2024-10-09 15:57:01,391 | INFO | check_semantic_version.check_semantic_version] Getting current version from '/github/workspace/pyproject.toml'.
[2024-10-09 15:5[7](https://github.com/octue/octue-sdk-python/actions/runs/11258547471/job/31305752555#step:4:8):02,140 | INFO | check_semantic_version.check_semantic_version] Current version: 0.60.1
[2024-10-09 15:57:02,141 | WARNING | check_semantic_version.check_semantic_version] No `mkver.conf` file found. Generating one instead.
[2024-10-09 15:57:02,143 | INFO | check_semantic_version.check_semantic_version] `mkver.conf` file created at '/tmp/tmp2y4fi[8](https://github.com/octue/octue-sdk-python/actions/runs/11258547471/job/31305752555#step:4:9)ct'.
Traceback (most recent call last):
  File "/check_semantic_version/check_semantic_version.py", line 142, in _get_expected_semantic_version
    process = subprocess.run(["git-mkver", "-c", config_path, "next"], capture_output=True, check=True)
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git-mkver', '-c', '/tmp/tmp2y4fi8ct', 'next']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/check-semantic-version", line 8, in <module>
    sys.exit(main())
  File "/check_semantic_version/cli.py", line 3[9](https://github.com/octue/octue-sdk-python/actions/runs/11258547471/job/31305752555#step:4:10), in main
    match = check_versions_match(args.path, args.breaking_change_indicated_by)
  File "/check_semantic_version/check_semantic_version.py", line 56, in check_versions_match
    expected_semantic_version = _get_expected_semantic_version(
  File "/check_semantic_version/check_semantic_version.py", line 144, in _get_expected_semantic_version
    raise CalledProcessError(returncode=e.returncode, cmd=e.cmd, output=e.output, stderr=e.stderr)
check_semantic_version.check_semantic_version.CalledProcessError: Command '['git-mkver', '-c', '/tmp/tmp2y4fi8ct', 'next']' returned non-zero exit status 1. Stderr: b''
```

**Comment by cortadocodes** [comment]
I've just checked that version `1.0.0.beta-9` of the action still works. I'll look into the diff between the latest version and that version
